apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-environment-systempolicy
  namespace: {{ .Values.namespace }}
data:
  policies.cedar: |-
{{ .Files.Get "files/rhea/policies.cedar" | indent 4 }}
